version: '2'
services:
  postgres:
    image: postgres:9.5
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chathub
    volumes:
      - /var/lib/postgresql

  redis:
    image: luizkowalski/redis-cache
    ports:
      - "6379"
    volumes:
      - /data

  chathub:
    build: .
    ports:
      - "8080"
    links:
      - redis
      - postgres
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_URL: jdbc:postgresql://postgres:5432/chathub
      MIXPANEL_TOKEN: invalid

  lb:
    image: 'dockercloud/haproxy:1.5.1'
    links:
      - chathub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
