postgres:
  image: postgres:9.5
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: chathub
  volumes:
    - /var/lib/postgresql
    
rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"
  volumes:
    - /var/lib/rabbitmq/
  environment:
    RABBITMQ_DEFAULT_USER: docker
    RABBITMQ_DEFAULT_PASS: docker
    
redis: 
  image: redis:alpine
  ports:
    - "6379:6379"
  volumes:
    - /src/main/resources/redis.conf:/usr/local/etc/redis/redis.conf
    - /data

chathub: 
  build: .
  ports:
    - "8080:8080"
  links:
    - redis
    - postgres
    - rabbitmq