version: 2
services: 
  postgres: 
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chathub
    volumes:
      - /var/lib/postgresql

  redis:
    image: luizkowalski/redis-cache
    ports:
      - "6379:6379"
    volumes:
      - /data

  chathub:
    build: .
    ports:
      - "8080"
    links:
      - redis
      - postgres  

  lb:
    image: 'dockercloud/haproxy:1.2.1'
    links:
      - chathub
    ports:
      - '80:80'
