spring:
  profiles:
    active: dev
  jackson.serialization.WRAP_ROOT_VALUE: true
  cache.cache-names: roomByUid, users
  cache.caffeine.spec: maximumSize=100, expireAfterAccess=10s  

github:
 client: ${GITHUB_CLIENT_KEY}
 secret: ${GITHUB_SECRET_KEY}
 
server: 
  compression.enabled: true
  port: 8080

mixpanel: 
  token: invalid

params:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    maximumPoolSize: 10
    poolName: chathub_conn_pool

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    
logging.level.org:
  springframework.web: INFO
  hibernate: INFO

---

spring:
  profiles: dev

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub

cache:
  host: localhost
  port: 6379

---

spring:
  profiles: test

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub_test

cache:
  host: localhost
  port: 6379
  
---

spring:
  profiles: cloud_test

params:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: qwerty
    jdbcUrl: jdbc:mysql://mysql:3306/chathub_test?createDatabaseIfNotExist=true

cache:
  host: localhost
  port: 6379

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: create-drop

---

# Production
spring:
  profiles: docker

cache:
  host: redis
  port: 6379

mixpanel:
  token: ${MIXPANEL_TOKEN}

params:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbcUrl: ${DATABASE_URL}
