spring:
  profiles.active: default

server:
  compression.enabled: true
  port: 8080

params:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    maximumPoolSize: 5
    poolName: hikari_pool

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

---

spring:
  profiles: default

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: test
  password: test

cache:
  host: localhost
  port: 6379

---

spring:
  profiles: docker

cache:
  host: redis
  port: 6379

params:
  datasource:
    jdbcUrl: jdbc:postgresql://postgres/chathub
    # jdbcUrl: jdbc:postgresql://${POSTGRES_ENV_DOCKERCLOUD_CONTAINER_FQDN}/chathub

spring.rabbitmq:
  host: rabbitmq
  # host: ${RABBITMQ_ENV_DOCKERCLOUD_CONTAINER_FQDN}
  port: 5672
  username: docker
  password: docker
