spring:
  profiles:
    active: dev
  data.mongodb.uri: mongodb://127.0.0.1/chathub_dev

server:
  compression.enabled: true
  port: 8080
  jetty.acceptors: 400

cache:
  host: ${CACHE_HOST:127.0.0.1}
  port: ${CACHE_PORT:6379}

mixpanel:
  token: invalid

logging.level.org:
  springframework.web: INFO
  

---

spring:
  profiles: dev

---

spring:
  profiles: cloud_test
  data.mongodb.uri: mongodb://mongo/chathub_cloud_test

---

spring:
  profiles: test
  data.mongodb.uri: mongodb://127.0.0.1/chathub_dev_test

---

# Production
spring:
  profiles: docker
  data.mongodb.uri: ${MONGO_URI}

mixpanel:
  token: ${MIXPANEL_TOKEN}
