spring:
  profiles.active: default

---
server:
  compression.enabled: true

spring:
  profiles: default

params:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub
    username: postgres
    password: postgres
    maximumPoolSize: 10
    poolName: hikari_pool

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: test
  password: test
  
---
server:
  compression.enabled: true

spring:
  profiles: production
  
params:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: ${JDBC_URL}
    username:  ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    maximumPoolSize: 10

spring.jpa:
  show-sql: false
  hibernate:
    ddl-auto: update
    
spring.rabbitmq:
  addresses: ${RABBITMQ_BIGWIG_URL}