spring:
  application:
    name: chathub-api

server:
  compression.enabled: true
  port: 8080

logging.level.org.springframework.cloud.sleuth: DEBUG

cache:
  host: 127.0.0.1
  port: 6379

mixpanel:
  token: invalid

params:
  datasource:
    username: postgres
    password: postgres
    maximumPoolSize: 10
    poolName: chathub_conn_pool
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

logging.level.org:
  springframework.web: INFO
  hibernate: INFO