spring:
  profiles.active: default

server:
  compression.enabled: true
  port: 8080
  
mixpanel: 
  token: ${MIXPANEL_TOKEN}

params:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    maximumPoolSize: 10
    poolName: chathub_conn_pool

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

---

spring:
  profiles: default

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub

cache:
  host: localhost
  port: 6379

---

spring:
  profiles: docker

cache:
  host: redis
  port: 6379

params:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbcUrl: ${DATABASE_URL}