spring:
  profiles.active: default

server:
  compression.enabled: true
  
params:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    maximumPoolSize: 5
    poolName: hikari_pool

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    
---

spring:
  profiles: default

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: test
  password: test
 
redis: 
  host: localhost
  port: 6379
  
---

spring:
  profiles: docker
  
params:
  datasource:
    jdbcUrl: jdbc:postgresql://postgres/chathub
    
redis: 
  host: redis
  port: 6379

spring.rabbitmq:
  host: ${RABBITMQ_1_PORT_5671_TCP_ADDR}
  port: 5672
  username: docker
  password: docker