spring:
  profiles:
    active: dev
  jackson.serialization.WRAP_ROOT_VALUE: true
  cache.cache-names: roomByUid, users
  cache.caffeine.spec: maximumSize=100, expireAfterAccess=10s  

server: 
  compression.enabled: true
  port: 8080

mixpanel: 
  token: invalid

params:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    maximumPoolSize: 10
    poolName: chathub_conn_pool

spring.jpa: 
  show-sql: true
  properties: 
   eclipselink:
     # persistence-context.flush-mode: COMMIT
     weaving: false
     ddl-generation: create-or-extend-tables
     logging:
       parameters: true
       level: 
         sql: FINEST
         query: FINEST
    
logging.level.org:
  springframework.web: INFO
  hibernate: INFO

---

spring:
  profiles: dev

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub

---

spring:
  profiles: cloud_test

params:
  datasource:
    username: postgres
    password: qwerty
    jdbcUrl: jdbc:postgresql://postgres:5432/chathub_test
 
---

spring:
  profiles: test

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub_test

---

# Production
spring: 
  profiles: docker

mixpanel:
  token: ${MIXPANEL_TOKEN}

params:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbcUrl: ${DATABASE_URL}
