spring:
  profiles:
    active: dev

server:
  compression.enabled: true
  port: 8080
  
mixpanel: 
  token: ${MIXPANEL_TOKEN}

params:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    maximumPoolSize: 10
    poolName: chathub_conn_pool

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

---

spring:
  profiles: dev

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub

cache:
  host: localhost
  port: 6379

---

spring:
  profiles: test
  
params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub_test

cache:
  host: localhost
  port: 6379

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: create-drop

---

# Production

spring:
  profiles: docker
    
cache:
  host: redis
  port: 6379

params:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbcUrl: ${DATABASE_URL}