spring:
  profiles.active: default

---
spring:
  profiles: default
  
spring.datasource:
  url: jdbc:postgresql://localhost:5432/chatroom
  username: postgres
  password: postgres
  platform: postgres
 
spring.database:
  driverClassName: org.postgresql.Driver

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: test
  password: test
  
---
spring:
  profiles: production
  
spring.datasource:
  url: ${JDBC_URL}
  username: ${JDBC_USER}
  password: ${JDBC_PASSWORD}
  driverClassName: org.postgresql.Driver
  platform: postgres

spring.jpa:
  show-sql: false
  hibernate:
    ddl-auto: update
    
spring.rabbitmq:
  addresses: ${RABBITMQ_BIGWIG_URL}