spring:
  profiles:
    active: dev

server:
  compression.enabled: true
  port: 8080
  jetty.acceptors: 400

cache:
  host: ${CACHE_HOST:127.0.0.1}
  port: ${CACHE_PORT:6379}

mixpanel:
  token: invalid

params:
  datasource:
    username: postgres
    password: postgres
    maximumPoolSize: 100
    poolName: chathub_conn_pool

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

logging.level.org:
  springframework.web: INFO
  hibernate: INFO

---

spring:
  profiles: dev

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub

---

spring:
  profiles: cloud_test

params:
  datasource:
    username: postgres
    password: qwerty
    jdbcUrl: jdbc:postgresql://postgres:5432/chathub_test

---

spring:
  profiles: test

params:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/chathub_test

---

# Production
spring:
  profiles: docker

mixpanel:
  token: ${MIXPANEL_TOKEN}

params:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbcUrl: ${DATABASE_URL}
